### ISSUE TITLE
Does tcpcopy support services that maintain long connections?

### ISSUE THREAD

**Issue by cobolbaby** [peiwal11/tcpcopy_implement#4]

**Comment by peiwal11** [comment]
To answer this question, I need to clarify which type of long connections you are referring to. Do you mean the long connection between the client and the online server, or the connection between the online server and the assistant server, or another type of connection? Please provide more details so that I can better address your question.

Thank you!

**Comment by cobolbaby** [comment]
I mean the connection from the client to the server is a long connection, such as a database connection or a websocket connection.

**Comment by peiwal11** [comment]
[tcpcopy github](https://github.com/session-replay-tools) includes many issues related to your problem.
Based on information of issues, seems like TCPCOPY does not support long connections.
Here are several links may assist you.
1. https://github.com/session-replay-tools/tcpcopy/issues/377
2. https://github.com/session-replay-tools/tcpcopy/issues/209
3. https://github.com/session-replay-tools/tcpcopy/issues/276
